# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- name: system.debug
  value: true 

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'eShopOnWeb.sln'
    feedsToUse: 'select'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mickael-caro16778'
    scannerMode: 'MSBuild'
    projectKey: 'eshop-get-msbuild-version'
    projectName: 'eshop-get-msbuild-version'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'eShopOnWeb.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    arguments: '--collect "Code Coverage"'

- task: SonarCloudAnalyze@1