# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- name: system.debug
  value: true 

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'eShopOnWeb.sln'
    feedsToUse: 'select'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'DownloadsFolder_SQ_MultipleEditions'
    scannerMode: 'MSBuild'
    projectKey: 'plop'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'eShopOnWeb.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    arguments: '--collect "Code Coverage"'

- task: SonarQubeAnalyze@4

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'